rvm:
- 1.8.7
- 1.9.2
gemfile:
- Gemfile
env:
- DB=mongodb
- DB=redis
- DB=mysql
#- DB=postgres
before_script:
- "mysql -e 'create database vanity_test;' >/dev/null"
#- "psql -c 'create database vanity_test;' -U postgres >/dev/null"
